/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NIL = 8;
  /** RegularExpression Id. */
  int CONS = 9;
  /** RegularExpression Id. */
  int LAZYCONS = 10;
  /** RegularExpression Id. */
  int MATCH = 11;
  /** RegularExpression Id. */
  int BAR = 12;
  /** RegularExpression Id. */
  int SARROW = 13;
  /** RegularExpression Id. */
  int LET = 14;
  /** RegularExpression Id. */
  int TYPE = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int STAR = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int LPAR = 22;
  /** RegularExpression Id. */
  int RPAR = 23;
  /** RegularExpression Id. */
  int LBRA = 24;
  /** RegularExpression Id. */
  int RBRA = 25;
  /** RegularExpression Id. */
  int EQUAL = 26;
  /** RegularExpression Id. */
  int DOT = 27;
  /** RegularExpression Id. */
  int COLON = 28;
  /** RegularExpression Id. */
  int SEMIC = 29;
  /** RegularExpression Id. */
  int TERM = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int OR = 33;
  /** RegularExpression Id. */
  int EQ = 34;
  /** RegularExpression Id. */
  int GT = 35;
  /** RegularExpression Id. */
  int LT = 36;
  /** RegularExpression Id. */
  int GTEQ = 37;
  /** RegularExpression Id. */
  int LTEQ = 38;
  /** RegularExpression Id. */
  int DIF = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int ASSIGN = 41;
  /** RegularExpression Id. */
  int BOX = 42;
  /** RegularExpression Id. */
  int IF = 43;
  /** RegularExpression Id. */
  int ELSE = 44;
  /** RegularExpression Id. */
  int WHILE = 45;
  /** RegularExpression Id. */
  int PRINT = 46;
  /** RegularExpression Id. */
  int PRINTLN = 47;
  /** RegularExpression Id. */
  int FN = 48;
  /** RegularExpression Id. */
  int ARROW = 49;
  /** RegularExpression Id. */
  int INT = 50;
  /** RegularExpression Id. */
  int UNIT = 51;
  /** RegularExpression Id. */
  int BOOL = 52;
  /** RegularExpression Id. */
  int STRING = 53;
  /** RegularExpression Id. */
  int LIST = 54;
  /** RegularExpression Id. */
  int REF = 55;
  /** RegularExpression Id. */
  int UNION = 56;
  /** RegularExpression Id. */
  int STRUCT = 57;
  /** RegularExpression Id. */
  int String = 58;
  /** RegularExpression Id. */
  int Label = 59;
  /** RegularExpression Id. */
  int Id = 60;
  /** RegularExpression Id. */
  int Num = 61;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "<token of kind 6>",
    "\"*/\"",
    "\"nil\"",
    "\"::\"",
    "\":?\"",
    "\"match\"",
    "\"|\"",
    "\"->\"",
    "\"let\"",
    "\"type\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"~=\"",
    "\"~\"",
    "\":=\"",
    "\"box\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"=>\"",
    "\"int\"",
    "\"()\"",
    "\"bool\"",
    "\"string\"",
    "\"list\"",
    "\"ref\"",
    "\"union\"",
    "\"struct\"",
    "<String>",
    "<Label>",
    "<Id>",
    "<Num>",
  };

}
