/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NIL = 5;
  /** RegularExpression Id. */
  int CONS = 6;
  /** RegularExpression Id. */
  int LAZYCONS = 7;
  /** RegularExpression Id. */
  int MATCH = 8;
  /** RegularExpression Id. */
  int BAR = 9;
  /** RegularExpression Id. */
  int SARROW = 10;
  /** RegularExpression Id. */
  int LET = 11;
  /** RegularExpression Id. */
  int TYPE = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int STAR = 17;
  /** RegularExpression Id. */
  int DIV = 18;
  /** RegularExpression Id. */
  int LPAR = 19;
  /** RegularExpression Id. */
  int RPAR = 20;
  /** RegularExpression Id. */
  int LBRA = 21;
  /** RegularExpression Id. */
  int RBRA = 22;
  /** RegularExpression Id. */
  int EQUAL = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int COLON = 25;
  /** RegularExpression Id. */
  int SEMIC = 26;
  /** RegularExpression Id. */
  int TERM = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int GT = 32;
  /** RegularExpression Id. */
  int LT = 33;
  /** RegularExpression Id. */
  int GTEQ = 34;
  /** RegularExpression Id. */
  int LTEQ = 35;
  /** RegularExpression Id. */
  int DIF = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int ASSIGN = 38;
  /** RegularExpression Id. */
  int BOX = 39;
  /** RegularExpression Id. */
  int IF = 40;
  /** RegularExpression Id. */
  int ELSE = 41;
  /** RegularExpression Id. */
  int WHILE = 42;
  /** RegularExpression Id. */
  int PRINT = 43;
  /** RegularExpression Id. */
  int PRINTLN = 44;
  /** RegularExpression Id. */
  int FN = 45;
  /** RegularExpression Id. */
  int ARROW = 46;
  /** RegularExpression Id. */
  int INT = 47;
  /** RegularExpression Id. */
  int UNIT = 48;
  /** RegularExpression Id. */
  int BOOL = 49;
  /** RegularExpression Id. */
  int STRING = 50;
  /** RegularExpression Id. */
  int LIST = 51;
  /** RegularExpression Id. */
  int REF = 52;
  /** RegularExpression Id. */
  int UNION = 53;
  /** RegularExpression Id. */
  int STRUCT = 54;
  /** RegularExpression Id. */
  int String = 55;
  /** RegularExpression Id. */
  int Id = 56;
  /** RegularExpression Id. */
  int Num = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"nil\"",
    "\"::\"",
    "\":?\"",
    "\"match\"",
    "\"|\"",
    "\"->\"",
    "\"let\"",
    "\"type\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"~=\"",
    "\"~\"",
    "\":=\"",
    "\"box\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"=>\"",
    "\"int\"",
    "\"()\"",
    "\"bool\"",
    "\"string\"",
    "\"list\"",
    "\"ref\"",
    "\"union\"",
    "\"struct\"",
    "<String>",
    "<Id>",
    "<Num>",
  };

}
